import type { LucideIconName } from './categoryIcons'

const EMOJI_TO_ICON: Record<string, LucideIconName> = {
  '🏠': 'home',
  '🏡': 'house',
  '🛋️': 'armchair',
  '🔑': 'key',
  '✈️': 'plane',
  '🏖️': 'palmtree',
  '🚗': 'car',
  '🚌': 'bus',
  '🎉': 'party-popper',
  '🎂': 'cake',
  '🍕': 'utensils',
  '☕': 'coffee',
  '🎵': 'music',
  '🎮': 'gamepad-2',
  '🐶': 'dog',
  '💻': 'laptop',
  '🎓': 'graduation-cap',
  '❤️': 'heart',
  '🌙': 'moon',
  '🔥': 'flame',
  '🌈': 'rainbow',
  '⚽': 'trophy',
  '🛒': 'shopping-cart',
  '🌿': 'leaf',
  '🪄': 'wand-sparkles',
  '📸': 'camera',
  '🎧': 'headphones',
  '🧳': 'luggage',
  '📁': 'folder',
  '✨': 'sparkles',
  '💡': 'lightbulb',
  '🛍️': 'shopping-bag',
  '💊': 'pill',
  '🌄': 'sunrise',
  '🧾': 'scroll-text',
  '🙈': 'eye-off',
}

const KNOWN_ICONS = new Set<string>([
  'home',
  'house',
  'armchair',
  'key',
  'plane',
  'palmtree',
  'car',
  'bus',
  'party-popper',
  'cake',
  'utensils',
  'coffee',
  'music',
  'gamepad-2',
  'dog',
  'laptop',
  'graduation-cap',
  'heart',
  'moon',
  'flame',
  'rainbow',
  'trophy',
  'shopping-cart',
  'leaf',
  'wand-sparkles',
  'camera',
  'headphones',
  'luggage',
  'folder',
  'sparkles',
  'lightbulb',
  'shopping-bag',
  'pill',
  'target',
  'layout-grid',
  'menu',
  'settings',
  'bell',
  'lock',
  'check',
  'x',
  'plus',
  'link',
  'more-vertical',
  'wallet',
  'users',
  'receipt',
  'scroll-text',
  'eye-off',
  'sunrise',
])

export function resolveIconName(
  raw?: string | null,
  fallback: LucideIconName = 'sparkles',
): LucideIconName {
  if (!raw) return fallback
  const trimmed = raw.trim()
  if (KNOWN_ICONS.has(trimmed)) return trimmed
  if (EMOJI_TO_ICON[trimmed]) return EMOJI_TO_ICON[trimmed]
  return fallback
}
